server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  application:
    name: VACCINATION-CENTER-SERVICE

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # The SQL dialect makes Hibernate generate better SQL for the chosen database
        ddl-auto : update # Hibernate ddl auto (create, create-drop, validate, update)
Uri:
  citizenService : http://localhost:8081/citizen/get/